### PR TITLE
increase build number to trigger CI build

### PR DESCRIPTION
**Pull request by FuzesiMate**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FuzesiMate** [comment]
@conda-forge-admin, please rerender

**Comment by FuzesiMate** [comment]
@conda-forge/core

**Comment by FuzesiMate** [comment]
@conda-forge-admin, please ping core team

**Comment by chrisburr** [comment]
I guess this was just to restart the failed build on master (due to missing dependencies)? If so I've restarted it manually and in general there is no need to bump the build number if it's just to retry a pipeline that failed recently with no other changes: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=279385&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81

@FuzesiMate I guess you meant to add yourself to the maintainers when you added this in https://github.com/conda-forge/staged-recipes/pull/14011. As `IncQueryLabs` is a organisation we can't give it merge rights to this repository so your username should be used instead (plus anyone else who should have access). Can you reset the build number to 0 and add edit the maintainers section? I'll then merge which will trigger the bots to give you maintainer rights on this repository.

**Comment by FuzesiMate** [comment]
> I guess this was just to restart the failed build on master (due to missing dependencies)? If so I've restarted it manually and in general there is no need to bump the build number if it's just to retry a pipeline that failed recently with no other changes: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=279385&view=logs&j=516f237f-98f1-50a4-0946-c43fe5437b81
> 
> @FuzesiMate I guess you meant to add yourself to the maintainers when you added this in [conda-forge/staged-recipes#14011](https://github.com/conda-forge/staged-recipes/pull/14011). As `IncQueryLabs` is a organisation we can't give it merge rights to this repository so your username should be used instead (plus anyone else who should have access). Can you reset the build number to 0 and add edit the maintainers section? I'll then merge which will trigger the bots to give you maintainer rights on this repository.

@chrisburr thank you for your help! I modified the maintainer section, could you please merge this PR?

**Pull request merged**
